version: 0.0
os: linux
files:
  - source: /
    destination: /home/my-node-app
permissions:
  - object: /home/my-node-app
    owner: root
    group: root
    mode: 777
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
