version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-node-app
permissions:
  - object: /home/ec2-user/my-node-app
    owner: ec2-user
    group: ec2-user
    mode: 777
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 400
      runas: ec2-user
