version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    - 'scripts/*'
    - 'appspec.yml'
    - cat appspec.yml
  base-directory: '.'
